theme = "catppuccin_mocha"

[editor]
scrolloff = 8

[editor.cursor-shape]
insert = "bar"

[keys.normal]
A-d = "delete_selection"
d = "delete_selection_noyank"
A-c = "change_selection"
c = "change_selection_noyank"