import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations_theme_variant = "Dark"
padding = { x = 8, y = 8 }
dynamic_padding = true
dimensions = { columns = 120, lines = 30 }

[font]
normal = { family = "MonaspiceNe Nerd Font", style ="Regular"}
size = 12
offset.y = 4 
